"""empty message

Revision ID: ae2fdc2db22c
Revises: 
Create Date: 2022-11-07 18:32:40.570658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2fdc2db22c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('make', sa.String(length=150), nullable=False))
    op.add_column('car', sa.Column('model', sa.String(length=200), nullable=True))
    op.add_column('car', sa.Column('year', sa.String(length=20), nullable=True))
    op.add_column('car', sa.Column('color', sa.String(length=200), nullable=True))
    op.drop_column('car', 'email')
    op.drop_column('car', 'name')
    op.drop_column('car', 'address')
    op.drop_column('car', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('car', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('car', 'color')
    op.drop_column('car', 'year')
    op.drop_column('car', 'model')
    op.drop_column('car', 'make')
    # ### end Alembic commands ###
